#%RAML 1.0 Trait
headers:
  correlationid:
    type: string
    required: true
    example: "sdfs-ffdsh-dfskdsj"
    minLength: 1
    maxLength: 35
  client_id:
    type: string
    required: false
    example: "b23445sdhjewrwxjsd2345sadj324536"
    minLength: 1
    maxLength: 50
  client_secret:
    type: string
    required: false
    example: "b23445sdhjewrwxjsd2345sadj324536"  
    minLength: 1
    maxLength: 50 
  appName:
    type: string
    required: true
    example: "CLOS"
    minLength: 1
    maxLength: 35
  
  
  
      
