#%RAML 1.0 Trait
queryParameters:
  projectNumber:
    type: number | string | nil
    required: false   
    example: 123456
  reraNumber: 
    type: string | number | nil
    required: false
    example: "P0010023456789"
  projectName:
    required: false
    type: string | number | nil
    example: "RUNWAL"
  state: 
    type: string | number | nil
    required: false
    example: "MS"
  district:
    type: string | number | nil
    required: false
    example: "THANE"
  city:
    type: string | number | nil
    required: false
    example: "THANE"

      



  

   
