#%RAML 1.0 Library
types:
  output:
    type: object
    properties:
      correlationId:
        description: correlationId
        type: string
        required: true
      timpstamp:
        description: timpstamp
        type: string
        required: true
      appName:
        type: string
        required: false
      statusCode:
        description: statusCode
        type: number
        required: false
      statusMsg:
        description: statusMsg
        type: string
        required: true

